spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: baeldung
          uri: baeldung.com
          predicates:
            - Path=/baeldung/
        - id: myOtherRouting
          uri: localhost:9999