server:
  port: 8081
  servlet:
    context-path: /resource-server-jwt
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          auth: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/springoauth2
#actuator
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
  endpoints:
    web:
      exposure:
        include: *
        exclude: loggers
security:
  user:
    name: admin
    password: secret
    role: SUPERUSER

